project:
    type: website

website:
  description: "A blog built with Quarto"
  site-url: https://basics2022.github.io/myblog # you must change this appropriately for RSS feeds to work properly
  title: "basics blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Basics2022
#     - icon: twitter
#       href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



